[build]
  command = "echo 'Build complete'"
  publish = "."

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/submit-form"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
