[build]
  command = "cp templates/* . && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/submit-form"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
